### PR TITLE
document new dlopen feature and packaging

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by decathorpe** [comment]
Hey, coming here from the "Fedora Devel" matrix room. (I'm the main Rust package maintainer in Fedora.)

---

You could simplify those cfg-expressions a little, by using some shortcuts documented here:
https://doc.rust-lang.org/reference/conditional-compilation.html

In particular, `cfg(target_family = "windows")` is equivalent to just using `cfg(windows)`.

I've also very rarely seen `target_vendor` used anywhere in the Rust ecosystem, most multiplatform crates handle this differently. A [GitHub code search](https://github.com/search?q=%22target_vendor%22+filename%3ACargo.toml&type=code) yields only 185 results for usage of `target_vendor` in Cargo.toml files, and most of those only use it to gate things for WebAssembly environments. A search for `target_os` on the other hand yields thousands of results. For example, the `winit` crate does this to check for "apple platforms":

`[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]`

I'm not even sure if `target_vendor = "apple"` even checks for the same thing here, checking for ios and macos explicitly might be good (if that's what you want). The second dependency is also a bit weird in that it states where this should **not** be used, instead of where it **should** be used. Inverting that might make it easier to understand for readers.

You could use something like this:

```toml
[target.'cfg(any(windows, target_os = "ios", target_os = "macos"))'.dependencies]
# Load libjack at runtime.
jack = "0.9"

[target.'cfg(all(unix, not(any(target_os = "ios", target_os = "macos"))))'.dependencies]
# Link libjack at build time.
jack = { version = "0.9", default-features = false }
```

This should be equivalent to what you wanted to say in the first place:

- first snippet: for Windows, Mac OS, and iOS
- second snippet: for all Unix-y platforms (except Mac OS and iOS)

Not really "simplified" on the whole, as I first implied, but I think it should be easier to understand for readers 😅  Hope that makes sense.

**Comment by Be-ing** [comment]
Thanks for reviewing this @decathorpe. I also got useful feedback on the language in #lad on Libera Chat from people who know much more about JACK than I do. :sweat_smile: 

I like the suggestion to use the `cfg(windows)` shorthand. Unfortunately TOML doesn't allow to break these lines and they can become [ridiculously long](https://github.com/PolyMeilex/rfd/blob/6ca088a376a03372f8019440640fe84476d5ee26/Cargo.toml#L42).

There are actually quite a bit of Apple targets supported by Rust which all use `apple` as the `target_vendor`. From the [list of targets](https://doc.rust-lang.org/stable/rustc/platform-support.html):
  * x86_64-apple-darwin
  * aarch64-apple-darwin
  * aarch64-apple-ios
  * aarch64-apple-ios-sim
  * x86_64-apple-ios (This exists?)
  * aarch64-apple-ios-macabi
  * aarch64-apple-tvos
  * armv7-apple-ios
  * armv7s-apple-ios
  * i386-apple-ios
  * i686-apple-darwin
  * x86_64-apple-ios-macabi
  * x86_64-apple-tvos

AFAIK nobody has ported JACK to iOS or tvOS, but I suppose it is theoretically possible so I think the bindings should be prepared for that. Also `target_vendor = "apple"` is simpler than `any(target_os = "macos", target_os = "ios", target_os = "tvos")`.

**Comment by Be-ing** [comment]
I think you're misunderstanding the purpose of the environment variable. The point is to let someone building a downstream application choose whether to enable the `dlopen` feature without needing to pass down the feature through the Cargo.toml of the application and its dependency graph leading down to this crate. The recommendation is still to *not* use `dlopen` by default on Linux. The environment variable allows turning on it just for cross compiling. Refer to [this discussion](https://github.com/slint-ui/slint/pull/956#discussion_r807650892).

**Comment by Be-ing** [comment]
ping @wmedrano

**Comment by Be-ing** [comment]
Thanks for merging. Glad we got this working.

**Pull request merged**
