### PR TITLE
Improve ringbuffer usefulness.

### LINKED ISSUE #128: RingBuffer can't move between threads?
I'm playing with using jack's ringbuffer, I'm getting an error when I try to move a `RingBufferReader` between threads. Has anyone else had success using it?

I had a look at [`ringbuffer.c`](https://github.com/jackaudio/jack1/blob/master/libjack/ringbuffer.c) source and there is no synchronization at all! I think the implementation relies on the pointer incrementing operations being atomic (i.e. you can't observe a pointer that's been "half incremented"). I think the implementation is correct (reader/writer is `Send` but not `Sync`), just need to work out how to tell the compiler that. 

This is the error I got

<details><summary>rustc error using ringbuffer</summary>

```
error[E0277]: `*mut jack_sys::Struct_Unnamed12` cannot be sent between threads safely
   --> src/main.rs:115:30
    |
115 |     let jack_handle = client.activate_async((), audio)?;
    |                              ^^^^^^^^^^^^^^ `*mut jack_sys::Struct_Unnamed12` cannot be sent between threads safely
    |
    = help: within `jack::ringbuffer::RingBuffer`, the trait `std::marker::Send` is not implemented for `*mut jack_sys::Struct_Unnamed12`
    = note: required because it appears within the type `jack::ringbuffer::RingBuffer`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::sync::Arc<jack::ringbuffer::RingBuffer>`
    = note: required because it appears within the type `jack::ringbuffer::RingBufferWriter`
    = note: required because it appears within the type `Audio`

error[E0277]: `*mut jack_sys::Struct_Unnamed12` cannot be shared between threads safely
   --> src/main.rs:115:30
    |
115 |     let jack_handle = client.activate_async((), audio)?;
    |                              ^^^^^^^^^^^^^^ `*mut jack_sys::Struct_Unnamed12` cannot be shared between threads safely
    |
    = help: within `jack::ringbuffer::RingBuffer`, the trait `std::marker::Sync` is not implemented for `*mut jack_sys::Struct_Unnamed12`
    = note: required because it appears within the type `jack::ringbuffer::RingBuffer`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::sync::Arc<jack::ringbuffer::RingBuffer>`
    = note: required because it appears within the type `jack::ringbuffer::RingBufferWriter`
    = note: required because it appears within the type `Audio`

error: aborting due to 2 previous errors; 2 warnings emitted
```
</details>

### PR DESCRIPTION
**Pull request by derekdreery**
In particular, simplify the implementation using atomics to track destruction, and implement the safe `Sync` for all types.

Note that `Sync` is safe to implement because all mutating operations already require a unique pointer (`&mut`).

Closes #128

### CODE REVIEW

**Comment by derekdreery** [comment]
I needed this patch to be able to move one half of the ringbuffer into the realtime callback.

**Comment by derekdreery** [comment]
Closes #128

**Comment by wmedrano** [comment]
This will be in the 0.6.4 release.

**Comment by wmedrano** [comment]
Srry, I mean its in the 0.6.5 release.

**Pull request merged**
